### ISSUE TITLE
Implement module system

### ISSUE THREAD

**Issue by pospi** [sacredcapital/rep_interchange#5]
Authors of computations don't want to have to copy/paste library code into every computation. The interchange should provide for storage of library modules to the local sourcechain, and a means to `import` them into other computations.

We may want to provide user-definable string-based addressing for computations in order to resolve the less readable `EntryHash` identifiers.

**Comment by mhuesch** [comment]
redundant with https://github.com/sacredcapital/rep_lang/issues/47.
