### ISSUE TITLE
Proof multi-step computations composed of multiple interchange inputs & outputs

### ISSUE THREAD

**Issue by pospi** [sacredcapital/rep_interchange#6]
We should be able to do something like https://github.com/sacredcapital/rep_lang/issues/57 but using separate calculations with statically stored results inbetween.

**Comment by mhuesch** [comment]
this is subsumed by #8, although that will only demonstrate multi-input/multi-output calculations over simple types.

however, we are already tracking user-defined types in https://github.com/sacredcapital/rep_lang/issues/54, and implementing that, plus #8, should subsume the entire issue here. closing.
