### ISSUE TITLE
Finalise interchange computation storage features

### ISSUE THREAD

**Issue by pospi** [sacredcapital/rep_interchange#7]
Epic for tracking tasks related to making the Holochain cultural computation authoring experience ergonomic from a data handling perspective.

**Comment by mhuesch** [comment]
this feels too vague to me to keep open, at the stage we are at (far away from people who aren't me, or who are not quite technical, interacting with the tools).

I also think some of these concerns will naturally be explored in the "directed experiments" of #8, #10, and more.
